title: Michael Sloan
email: mikesloan47@gmail.com
description: Musings of a software test engineer & musician.

twitter_username: meekkaal
github_username:  meekkaal

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

compress_html:
  blanklines: true


